# Site settings
title: Joel Morrice
email: no-em@il.com
description: A simple contact submission site.
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/joelmorrice
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
